CI: require mysql-client-8.0
Currently:
```
  ​sudo apt-get install -y mysql-client
 ​mysql --host 127.0.0.1 --port 3306 -uroot -e 'create user travis;'
 ​mysql --host 127.0.0.1 --port 3306 -uroot -e 'GRANT ALL PRIVILEGES ON arext_test.* TO travis;'
 ​rake test:mysql
 ​shell: /usr/bin/bash -e {0}
 ​env:
   ​DB_CONNECTION: mysql
   ​DB_HOST: 127.0.0.1
   ​DB_PORT: 3306
   ​DB_DATABASE: arext_test
   ​DB_USERNAME: travis
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
​mysql-client : Depends: mysql-client-8.0 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Error: Process completed with exit code 100.
```